# Generated by Django 4.0.4 on 2022-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Instrument',
        ),
    ]
