# Generated by Django 4.0.4 on 2022-05-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_rename_product_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.category'),
        ),
    ]
